BASE_URL                = "https://api.hypixel.net"
API_KEY_INFORMATION     = BASE_URL + "/key"
PLAYER_DATA             = BASE_URL + "/player"
FRIEND_LIST             = BASE_URL + "/friends"
RECENT_GAMES            = BASE_URL + "/recentgames"
CURRENT_ONLINE_STATUS   = BASE_URL + "/status"
GET_GUILD               = BASE_URL + "/guild"

SKYBLOCK_RES_BASE_URL   = BASE_URL + "/resources/skyblock"
COLLECTIONS             = SKYBLOCK_RES_BASE_URL + "/collections"
SKILLS                  = SKYBLOCK_RES_BASE_URL + "/skills"
ITEMS                   = SKYBLOCK_RES_BASE_URL + "/items"
ELECTION_MAJOR          = SKYBLOCK_RES_BASE_URL + "/election"
BINGO                   = SKYBLOCK_RES_BASE_URL + "/bingo"

SKYBLOCK_BASE_URL       = BASE_URL + "/skyblock"
SKYBLOCK_NEWS           = SKYBLOCK_BASE_URL + "/news"
AUCTION                 = SKYBLOCK_BASE_URL + "/auction"
ALL_AUCTIONS            = SKYBLOCK_BASE_URL + "/auctions"
ENDED_AUCTIONS          = SKYBLOCK_BASE_URL + "/auctions_ended"
BAZAAR                  = SKYBLOCK_BASE_URL + "/bazaar"
PROFILE_BY_UUID         = SKYBLOCK_BASE_URL + "/profile"
PROFILES_BY_PLAYER      = SKYBLOCK_BASE_URL + "/profiles"
BINGO_BY_PLAYER         = SKYBLOCK_BASE_URL + "/bingo"
FIRESALES               = SKYBLOCK_BASE_URL + "/firesales"
